### ISSUE TITLE
Refactor top-level function declarations in ajaxindex.php

### ISSUE THREAD

**Issue by morellam-dev** [VadaProject/application#11]
Anywhere in ajaxindex.php where a function (such as `restoreActivity` is declared, separate it (and its Rivals version) into its own file in the functions/ folder.

The relative path to db_config.php will need to change.

See commit [3cdec10f52](https://github.com/VadaProject/application/commit/3cdec10f52c86acaa19b4a16a9a73ba4be2b6d94) for an example.

**Comment by BraxtonMDevelops** [comment]
See pull-request#2

**Comment by morellam-dev** [comment]
Merged in PR https://github.com/VadaProject/application/pull/24
